[package]
name = "koblas"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.36"
color-eyre = "0.6.2"

[dependencies.redis]
version = "0.21.6"

[dependencies.tokio]
version = "1.21.1"
features = ["net", "macros", "io-util", "rt-multi-thread"]
