[package]
name = "koblas"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.4.1"
color-eyre = "0.6.2"
itertools = "0.10.5"

[dependencies.clap]
version = "4.0.6"
features = ["derive"]

[dependencies.rand_core]
version = "0.6.4"
features = ["std"]

[dependencies.serde]
version = "1.0.145"
features = ["derive"]

[dependencies.sqlx]
version = "0.6.2"
features = ["sqlite", "runtime-tokio-rustls"]

[dependencies.tokio]
version = "1.21.1"
features = ["net", "macros", "io-util", "rt-multi-thread"]
